### ISSUE TITLE
Error while updating property `display` on Android

### ISSUE THREAD

**Issue by stefanoeb** [conorhastings/react-native-syntax-highlighter#1]
Seems like Android native `<HorizontalScrollView>` element doesn't like to receive `display: 'block'` styles, and therefore is throwing an error.
![image](https://cloud.githubusercontent.com/assets/8941938/25618375/2fcbcbc2-2f1d-11e7-8e83-3167e735fc4f.png)

I'm not sure what to do to fix that, since on iOS seems to work just fine

**Comment by conorhastings** [comment]
I don't think we rely on the display property on either os so we can probably just remove it in the generateNewStylesheet function
