### ISSUE TITLE
Console errors in React Native Debug mode

### ISSUE THREAD

**Issue by ahetawal-p** [conorhastings/react-native-syntax-highlighter#12]
Hi @conorhastings,
Apologies for filing multiple issues. As I am really looking forward to integrate this highlighter in my current app.  
I am using below versions in my 

```
"react-native-syntax-highlighter": "^2.0.0",
"react-syntax-highlighter": "^7.0.1",
```

But when running my app under React Native debug mode, the console log is getting flooded with below message
```
VM651:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at prism-core.js:493
```

Although the highlighter view loads fine, but the console log seems to be bogged down with the error messages.
Would be great if this can be fixed.

Thank you again,

**Comment by conorhastings** [comment]
@ahetawal-p do you have a code sample?

**Comment by ahetawal-p** [comment]
Nothing specific, I just tried using the syntax-highlighter in one of my views

```
<SyntaxHighlighter
     language='java'
     style={dracula}
  >
  {codeString}
  </SyntaxHighlighter>
```

And in debug mode I start seeing flood of above error messages on chrome console.

Seems something related to the `prism-core.js` as soon as it gets imported in my app through highlighter, the console starts showing the messages

PS: Its seems to related this issue:
https://github.com/PrismJS/prism/issues/1303

**Comment by andrey-skl** [comment]
Have the same issue, it really doesn't let me debugging things

**Comment by conorhastings** [comment]
I know it's been a while, i've been busy with a move / new job / but it's on my todo list for this weekend, thanks for the patience.

**Comment by mehulmpt** [comment]
Still the same. Any update on this?

**Comment by KonstantinZhukovskij** [comment]
any news here?

**Comment by chaitanya71998** [comment]
any update on this issue? @chrisglein

**Comment by chrisglein** [comment]
> any update on this issue? @chrisglein

Fix has been merged. There hasn't been a NPM release that includes it yet.

**Comment by chaitanya71998** [comment]
Thanks @chrisglein  , can i know how to use package in this case without clonning?

**Comment by chaitanya71998** [comment]
@chrisglein ?
