### ISSUE TITLE
Slow Rendering

### ISSUE THREAD

**Issue by Kida007** [conorhastings/react-native-syntax-highlighter#14]
on a device without development mode, when I navigate to a screen with SyntaxHighlighter (conditional rendering ), the UI freezes for a second.  but that single glitch, everything works fine. 

is there a way to preload it ?

**Comment by lefrankleal** [comment]
have you found the way?

**Comment by Kida007** [comment]
sorry,  I have not really followed up on that !

**Comment by myhamdaoui** [comment]
I suggest using a loader, once the componenet mounts you render the `SyntaxHighlighter ` else you render the loader
