### ISSUE TITLE
value.includes is not a function at nativesyntaxhighlighter

### ISSUE THREAD

**Issue by iaravindreddyp** [conorhastings/react-native-syntax-highlighter#16]
iam trying to use the package but there seems to be an error in source code 

> TypeError: TypeError: value.includes is not a function

This error is located at:
    in NativeSyntaxHighlighter
    in RCTView (at View.js:45)
    in View (at ScrollView.js:953)
    in RCTScrollView (at ScrollView.js:1092)
    in ScrollView (at GestureHandler.js:395)
    in NativeViewGestureHandler (at GestureHandler.js:394)
    in ComponentWrapper (at FibBlockBody.js:79)
    in RCTView (at View.js:45)
    in View (at FibBlockBody.js:78)
    in RCTView (at View.js:45)
    in View (at FibBlockBody.js:74)
    in FibBlockBody (at Quiz.js:23)
    in RCTView (at View.js:45)
    in View (at ScrollView.js:953)
    in RCTScrollView (at ScrollView.js:1092)
    in ScrollView (at GestureHandler.js:395)
    in NativeViewGestureHandler (at GestureHandler.js:394)
    in ComponentWrapper (at Quiz.js:21)
    in RCTView (at View.js:45)
    in View (at Quiz.js:20)
    in App (created by SceneView)
    in SceneView (at StackViewLayout.js:795)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.js:69)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.js:57)
    in Card (at createPointerEventsContainer.js:27)
    in Container (at StackViewLayout.js:860)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.js:311)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.js:307)
    in PanGestureHandler (at StackViewLayout.js:300)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.js:79)
    in RCTView (at View.js:45)
    in View (at Transitioner.js:214)
    in Transitioner (at StackView.js:22)
    in StackView (created by Navigator)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:388)
    in NavigationContainer (at App.native.js:9)
    in Provider (at App.native.js:8)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

This error is located at:
    in NavigationContainer (at App.native.js:9)
    in Provider (at App.native.js:8)
    in App (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)
<unknown>
    
<unknown>
    _export.js:37:12
generateNewStylesheet
    _export.js:35:20
NativeSyntaxHighlighter
    _to-primitive.js:8:27
renderWithHooks
    ReactNativeRenderer-dev.js:9473:17
mountIndeterminateComponent
    ReactNativeRenderer-dev.js:11993:12
beginWork
    ReactNativeRenderer-dev.js:12835:13
performUnitOfWork
    ReactNativeRenderer-dev.js:17276:11

**Comment by lefrankleal** [comment]
no feedback's?

**Comment by iaravindreddyp** [comment]
@lefrankleal what do you mean ?

**Comment by lefrankleal** [comment]
@aravind1078 about how to solve this...
