### ISSUE TITLE
Coloring breaks the second time the SyntaxHighlighter component is rendered

### ISSUE THREAD

**Issue by gunn** [conorhastings/react-native-syntax-highlighter#6]
First render looks great:
![screen shot 2017-08-25 at 11 00 21 pm](https://user-images.githubusercontent.com/42500/29711515-511202b6-89e9-11e7-972b-9bfd61a96ec4.png)

Second render seems to lose its primary color:
![screen shot 2017-08-25 at 10 54 51 pm](https://user-images.githubusercontent.com/42500/29711385-9ec001c6-89e8-11e7-9fb7-099013ca426c.png)

**Comment by conorhastings** [comment]
@gunn thanks for the issue! fixed in `v1.2.5`
